/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.14";
const char *compilation_string = "gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/opt/mirrortools/tools/wget/etc/wgetrc\" -DLOCALEDIR=\"/opt/mirrortools/tools/wget/share/locale\" -I. -I../lib -I../lib -O2 -Wall";
const char *link_string = "gcc -O2 -Wall -lz -lrt ftp-opie.o ../lib/libgnu.a";
